### PR TITLE
Initiate validation pipeline

### PR DESCRIPTION
**Pull request by yannfeat**
Hi @dgkf,

Please see https://github.com/yannfeat/thevalidatoR/actions/runs/7584133956. You will see that 2 checks don't pass, I didn't manage to resolve the issue. Could you please help me? The call to remotes::install_local in the report template fails when attempting to install the dependency.

Thanks.

### CODE REVIEW

**Comment by dgkf** [comment]
Just documenting a discussion from today's meeting. @csgillespie suggested testing on a simpler package such as `drat`. I agree - I think the issues we're seeing might be due to the complexity of the package. It will be good to identify a simpler package with a fast test suite which will also help to iterate more quickly (another candidate I always reach for in such cases is the `praise` package)

**Comment by yannfeat** [comment]
I tried doing as you suggested, but the checks are still not passing. I think the issues is in fact due to the [validation template](https://github.com/yannfeat/thevalidatoR/blob/main/tests/packages/buckbeak/validation-template.Rmd) of the test package "buckbeak", which calls remotes::install_local: according to the log messages below, the installation is not going well. This was already the case when I tried to only download the source files of the package dependency without installing it myself. Maybe calling the Rmd file or the action changes the default library? I have stopped trying to fix this issue, as it might disappear on its own when we discard the Rmd files in favor of JSON templates.
image

**Comment by csgillespie** [comment]
Can you point to the log for me?

**Comment by yannfeat** [comment]
Sure: https://github.com/yannfeat/thevalidatoR/actions/runs/7784025452/job/21223736386

**Comment by yannfeat** [comment]
@csgillespie no need to spend more time on it: as I said, the issue resolved itself on its own when we switched to JSON artifacts.

**Pull request merged**
